version: "3.8"

services:
  nginx:
    image: nginx:1.21-alpine
    depends_on:
      - php-fpm
    ports:
      - "127.0.0.1:80:80"
    volumes:
      - ./etc/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/sloww/public

  php-fpm:
    image: 1maa/php:7.3
    volumes:
      - ./etc/php-fpm/php-fpm.conf:/etc/php/fpm/php-fpm.conf
      - ./etc/php-fpm/www.conf:/etc/php/fpm/php-fpm.d/www.conf
      - .:/var/www/sloww
    working_dir: /var/www/sloww
